### ISSUE TITLE
Beehive Textures are corrupted except vanilla one.

### ISSUE THREAD

**Issue by DoomShin** [pnk2u/More-Beehive-Variants#1]
![2024-12-07_16 34 22](https://github.com/user-attachments/assets/13ec210c-1eb7-425f-8b0e-91132d3c7954)
I used vanilla one for building because of corrupted textures.
Can you fix this?

**Comment by pnk2u** [comment]
Of course, so sorry for this - and thank you so much for bringing it to my attention, it is fixed in 1.1.2 which I just uploaded.
